[package]
name = "rash"
version = "0.1.0"
edition = "2021"

[dependencies]
num_cpus = "1"
crossbeam-channel = "0.5"
sha2 = "0.10.8"
env_logger = "0.10"
once_cell = "1.15"
clap = { version = "4.2", features = ["derive"] } # Add Clap with derive macros
glob =  "0.3.1"
log = "0.4.6"
